### ISSUE TITLE
How can we build emails for Newsletter

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#101]
How can we build emails for sending periodic Newsletter about Products on Regularshare,I suggest you integrate a pop up link that will request visitors to subscribe to newsletter

**Comment by serviceproviderpk** [comment]
what is your expected flow about it?

**Comment by serviceproviderpk** [comment]
We should create a page? you will enter some message on it and email will be send to all subscriber of the web site?
