### ISSUE TITLE
please post this Advert

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#105]
Land for sale at Ibeju-Lekki Lagos 
CALL NOW: 08137625124,09055862871
![euc-homes-flyers-for-8](https://cloud.githubusercontent.com/assets/19783574/17648045/1adbea14-6211-11e6-9786-68cea7551e42.jpg)

INTL NO: +905358372118,
E-MAIL: abdulfatee02@yahoo.com

**Comment by regularshare** [comment]
CALL NOW: 08137625124,09055862871
INTL NO: +905358372118
E-MAIL: abdulfatee02@yahoo.com

**Comment by serviceproviderpk** [comment]
for above add where you want put it?
in new page or some other place??

**Comment by regularshare** [comment]
place it in the upper side where visitor can see it

**Comment by serviceproviderpk** [comment]
its dimensions are two high. please send in width 768*90.
if we use as it is, it will make web site odd.

If positioned well, wide ad sizes can increase your earnings significantly. The sizes we've found to be the most effective are the 336x280 large rectangle, the 300x250 medium rectangle, the 728x90 leaderboard, the 300x600 half page, and on mobile the 320x100 large mobile banner.

**Comment by serviceproviderpk** [comment]
please send in above size, google also recommend above sizes.

**Comment by regularshare** [comment]
![new image](https://cloud.githubusercontent.com/assets/19783574/17678958/027762b4-6342-11e6-9965-c1c554a30f86.jpg)

**Comment by regularshare** [comment]
I will like you use this new image ,but I will like you to upload the first image in another page in which when someone click on the small image it will open a new image where they can see the full image clearly

**Comment by serviceproviderpk** [comment]
Ok.

I have reviwed GitHub points. Nasir already working on it. hopefully upto sunday your most of the task will be completed including dashboard summary.
