### ISSUE TITLE
the site still shows this image

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#106]
I will like you to remove the image that appear on the attached pictures from showing whenever i sent my site to people on social media or email ,it makes it look like a food site
![image](https://cloud.githubusercontent.com/assets/19783574/17688944/571fb948-638c-11e6-9092-4ac24f3e1abf.PNG)

**Comment by serviceproviderpk** [comment]
I tried to share on facebook, it is showing list of multiple images. you can choose any one if you want to share....

it is ok??

**Comment by regularshare** [comment]
Yes It OK Like that

**Comment by regularshare** [comment]
It does not show multiple images here , it shows one only
