### ISSUE TITLE
I want to bring some category to the top Menu

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#110]
Good Morning,

Kindly create another Top menu ,Name it Trending

Then Move the following menus and their sub under the Trending menu

* Mobile Menu
* Cricket Menu
* Finance Menu
* Food Menu
* Poetry Menu
* Islam Menu

Then Move the following category from Buy n sell to the Top Menu 

* Fashion Category
* Mobiles Category
* Appliances & Electronics Category

**Comment by serviceproviderpk** [comment]
Fixed
