### ISSUE TITLE
post from buy and sell

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#111]
I also want products from buy and sell to be display on the section shown on the attached image
![buy and sell](https://cloud.githubusercontent.com/assets/19783574/17764127/09e8bbde-6526-11e6-8e7f-cdbf9355333d.PNG)

**Comment by serviceproviderpk** [comment]
Ok.this is good option.

**Comment by serviceproviderpk** [comment]
Fixed
