### ISSUE TITLE
serious issues need your attention urgently

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#112]
Products posted on buy and selling sections are not showing on the website ,kindly fix this soon as possible

Thanks

**Comment by NasirNiazkiyani** [comment]
ok

**Comment by regularshare** [comment]
Dont forget to replace the section shown in the attached image with some categories from buy n sell such as :
Mobiles
Appliances and electronics
Furniture
Fashion
Real Estate

![wallpaper now](https://cloud.githubusercontent.com/assets/19783574/17829344/52f2eb8a-66b4-11e6-8895-b0848d823ea9.PNG)

**Comment by serviceproviderpk** [comment]
Fixed
