### ISSUE TITLE
buy n sell Issues

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#113]
when you are on a categories and there is need to navigate to another category , there should be a link right there without going back home ,study the attached image
![buy n sell category](https://cloud.githubusercontent.com/assets/19783574/17829740/2c439108-66c1-11e6-8e87-9c886b0fdd67.PNG)

**Comment by serviceproviderpk** [comment]
updated, please take a look and give your feedback.

Thanks
