### ISSUE TITLE
User Issues

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#17]
when a visitor register to become a user,once they login ;
they should have access to upload photos for the contest, 
see their vote and rating,
they should have access to buying and selling as well as live chat  
there should be an option to Navigate back to the Home page and other pages

All of the above should be working with clicking on Home .....but when i check they will have to click on dashboard which most people wont understand because they are already in the dashboard when they login ....please work on it by linking the Dashboard icon with the Home icon after Login

**Comment by serviceproviderpk** [comment]
Above featured added. Please let me know if any missing
