### ISSUE TITLE
Curreny converter Issue

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#19]
the currency converter section was only showing below countries and another website showing at the bottom which means people have to leave my site to another site to convert their money ,even my local currency was not showing in the list below,Kindly fix it in a way visitors will be able to do global currency converter on my website

USD - United States dollar	$	
1
 Euro	EUR - Euro	€	
0.89
 British pound	GBP - British pound	£	
0.70
 Japanese yen	JPY - Japanese yen	¥	
106.37
 Chinese yuan	CNY - Chinese yuan	¥	
6.59
 United States dollar	USD - United States dollar

**Comment by serviceproviderpk** [comment]
Fixed. now user cany select from any to any conversion
