### ISSUE TITLE
where do i edit the message sent to user when they register

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#20]
where do i Edit the message below : it the message sent to user when they register 

We welcome you to Regular Share
 
You can now buy our different products and various services we have to offer you. below is your account details:

**Comment by serviceproviderpk** [comment]
IN admin section in "Static pages" section i have added another textbox, where you can edit that text.
PLEASE NOT REMOVE THE TEXT THANT IS BEWTWEEN UNDER SCORE LIKE
__email__ etc...
