### ISSUE TITLE
Social Media Page

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#27]
please don't forget about the social media Page like ,Facebook,twitter,LinkedIn and Instagram set up

**Comment by serviceproviderpk** [comment]
https://plus.google.com/u/0/b/100468646211145339015
https://www.facebook.com/regulareshare/

**Comment by serviceproviderpk** [comment]
Above account setup with email info@regularshare.com
and password is same as i provided last time...

and linked with web site.
