### ISSUE TITLE
post an add screenshot

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#31]
see the post an add screenshot before the submit

![post an add screenshot](https://cloud.githubusercontent.com/assets/19783574/16181270/2ac5c9cc-36a1-11e6-9aa6-48e2a1946a4e.PNG)

**Comment by serviceproviderpk** [comment]
Try now, you need to select "Category", main category,subcategory and then add product Like

Like  "Mobile is product"

Main Category : Electrnoics
Category: Mobile
Subcategory: Nokia

similary you can mension the category from admin section....
