### ISSUE TITLE
please create a way of having more than one Admin

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#40]
please create a way of having more than one Admin whereby I can have like 2 or 3 admin.meanwhile only one admin will be super admin by having full access to the admin dashboard ,and 2 other admin will have access like add ,edit ,approve users,delete users,approve user post 

only the super admin will be able to assign or delete other admin .

super Admin.....Full access
other admin.....Limited Access

Thanks

**Comment by serviceproviderpk** [comment]
You can make any normal user to admin and any admin to nomral user.

i have sent credentials of super admin.

Thanks
