### ISSUE TITLE
Rss Links

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#45]
https://www.naij.com/

http://allafrica.com/misc/tools/rss.html

http://www.news24.com.ng/Site-Elements/Services/Subscribe-to-our-RSS-feeds-20130503

http://rss.thenigerianvoice.com/news.xml?cat_id=1&gender=28

http://rss.thenigerianvoice.com/news.xml?cat_id=1&gender=12

**Comment by serviceproviderpk** [comment]
rss alrady implemented
