### ISSUE TITLE
Issues arising

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#47]
when i click on interview under article menu ,it shows errors as shown in the picture attached,same thing happen when i click on sub-menus under finance menu,please help
![issues arrising](https://cloud.githubusercontent.com/assets/19783574/16362619/9ff18cc0-3bbc-11e6-92c8-6dcb1753fa35.PNG)

**Comment by serviceproviderpk** [comment]
we didnot face this issue
