### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#51]
please check the cause of this issues and solve it once and for all ,seems the problem is coming too much, I was in the admin dashboard ,I decide to click on members or newsletter then it shows the error as shown on the pictures
![problems](https://cloud.githubusercontent.com/assets/19783574/16365288/ba9f259e-3c04-11e6-8156-ff37e19170a3.PNG)

**Comment by serviceproviderpk** [comment]
Fixed.
