### ISSUE TITLE
Seach Link

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#52]
The attached image is the backend image of my other site ,Look at the attached image you will see the search link 
from the search link i can easy locate every menu in the admin backend , is it possible to have something like that on regularshare ?

![admin backend](https://cloud.githubusercontent.com/assets/19783574/16373534/76009bdc-3c5b-11e6-9046-8688e808ae04.PNG)

**Comment by serviceproviderpk** [comment]
i have added it.
