### ISSUE TITLE
latest Headlines

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#57]
The latest headline news was suppose to be selected automatically from the news posted daily but when i deleted the test news you posted there ...it all empty..Kindly fix to make it work

see the image 
![latest headlines](https://cloud.githubusercontent.com/assets/19783574/16413279/bb3585b2-3d39-11e6-9c2c-d107f1e02f78.PNG)

**Comment by serviceproviderpk** [comment]
Fixed.
