### ISSUE TITLE
Video Rotation

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#59]
I will like the video shown at the right hand side be rotating ,meanwhile i will like you to correct the video spelling , you have written it as vidoes instead of videos

see the attached image
![videos rotate](https://cloud.githubusercontent.com/assets/19783574/16414012/eea2f714-3d3d-11e6-8844-470323d24ec3.PNG)

**Comment by serviceproviderpk** [comment]
spelling fixed
