### ISSUE TITLE
password setting

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#65]
please look at this image you will see how i will like the password to look like in the admin 
the password will not be visible to the admin but there will be a check box where the admin manager can click to check any password 
![admin](https://cloud.githubusercontent.com/assets/19783574/16431745/a7ae9bc2-3d8a-11e6-8a5b-e931b2c1ae3a.PNG)

**Comment by serviceproviderpk** [comment]
updated
