### ISSUE TITLE
video spelling error

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#67]
see in the image please correct the spelling

the video spelling is not correct
![video spelling](https://cloud.githubusercontent.com/assets/19783574/16441003/54912bcc-3dcf-11e6-8d40-62975d0f6c28.PNG)

**Comment by regularshare** [comment]
You have not fixed it , check it again , you have only fix the other one

**Comment by serviceproviderpk** [comment]
please check and confirm.

Thanks
