### ISSUE TITLE
famous scholars

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#68]
Kindly make the famous scholar section editable so that we can easily edit it in case i may decide to put someone else or i can decide to place photo contest winners there 
![famous scholar](https://cloud.githubusercontent.com/assets/19783574/16452325/7d163862-3e10-11e6-9d59-79368c1e6144.PNG)

**Comment by serviceproviderpk** [comment]
Please in this section show "MediaSubCategory" when user click on  any subcategory show its related audio/video list
