### ISSUE TITLE
I see hamariweb.com

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#69]
check the attached image ,you will see hamariweb.com ,it shouldnt be there please remove it

and the Nigeria spelling in the image is not correct
 
![hamariweb error](https://cloud.githubusercontent.com/assets/19783574/16458159/cea85424-3e26-11e6-9078-219b5562dbef.PNG)

**Comment by serviceproviderpk** [comment]
Fixed.
