### ISSUE TITLE
photos issues

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#74]
some photos are not properly shown in the admin dashboard
![photos not proper](https://cloud.githubusercontent.com/assets/19783574/16499216/0f918424-3f08-11e6-8031-e3d5234cbf15.PNG)

**Comment by NasirNiazkiyani** [comment]
Fixed.....

**Comment by serviceproviderpk** [comment]
During account created. image was not added by the user.
i have set default image.

if user will not upload image, we will add default image.
