### ISSUE TITLE
enable my site for auto publishing

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#76]
Kindly enable my site for all post and articles posted on my site be automatically publish on twitter and facebook

Thanks

**Comment by serviceproviderpk** [comment]
This is out of scope of the project.

Thanks,

**Comment by regularshare** [comment]
I know ,send me the quote for it

**Comment by serviceproviderpk** [comment]
you prefer windows application ? or web  based application

**Comment by regularshare** [comment]
You should know the best ,you are the developer

**Comment by serviceproviderpk** [comment]
autoposting is enabled. now posting will be automatically posted on twitter and facebook page.

i will also guide how you can post on multiple facebook groups using auto posting features.
