### ISSUE TITLE
create search link or search menu

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#90]
![search](https://cloud.githubusercontent.com/assets/19783574/17025408/5e576026-4f64-11e6-9270-c7d9e89096f9.PNG)
there is need for you to create search link , this search link will be used to locate all the post or article posted by a particular member or staff ,please work this out soon as possible ,I have raised this issue before but still unresolved

**Comment by serviceproviderpk** [comment]
Ok. will add it and update you

**Comment by serviceproviderpk** [comment]
Implemented.
