### ISSUE TITLE
Do not delete the footer but rearrange

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#93]
do not delete the footer but I will like you to arrange it well and also describe to us how to edit the footer and I think it be better if the footer can automatically change by showing new post on the footer 

also I dont like the empty space as shown on the attached image,kindly rearrange the footer
![empty space](https://cloud.githubusercontent.com/assets/19783574/17090642/4e49caf0-523b-11e6-9ee0-fef55911588d.PNG)

**Comment by serviceproviderpk** [comment]
Fixed, please take a look and give your feedback.

Thanks
