### ISSUE TITLE
Rearrange this frontpage

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#94]
please rearrange the front page as shown in the attached picture
I want you to add a navigational menu to the area shown on the picture
![rearrange news](https://cloud.githubusercontent.com/assets/19783574/17212864/30be432a-54da-11e6-88fb-3d2cb6cce1c8.PNG)

![rearrange news](https://cloud.githubusercontent.com/assets/19783574/17212840/0f811f52-54da-11e6-93de-24dc4bf5f1be.PNG)

**Comment by serviceproviderpk** [comment]
these should be link?
or show in tab?

**Comment by regularshare** [comment]
please make it a shown Tab

**Comment by serviceproviderpk** [comment]
as we discussed, it will make web site ugly, we we add lot of tab. so i have ignoring this issue.
