### ISSUE TITLE
Can not be found in admin dashboard

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#95]
The following menus and their sub menus can not be found in the admin dashboard which means there is no way to add  articles or edit them

Mobile menus and sub
Food menu and subs
Poetry and subs

Kindly attend to these issues soon as possible

**Comment by serviceproviderpk** [comment]
Please login to the dasbhoard and click on "Artilce" > New Artilce > and then from dropdown you can select type

then you can add data.

Let me know if you face any issue in it
