### ISSUE TITLE
add embeded link

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#96]
please make it possible to add embeded links and videos from youtube and other social media

**Comment by serviceproviderpk** [comment]
When you will add audio/video there is an option
youtube embed code.
you can copy paste youtube script, if its not clear i can explain on 
skype call

Thank,

**Comment by serviceproviderpk** [comment]
this video is youtube video http://regularshare.com/AudioVideos/MediaFileDetail/50040

when you add code please mension width and height  like this

<iframe width="770" height="379" src="https://www.youtube.com/embed/aQHK8UZ52Zk" frameborder="0" allowfullscreen></iframe>

width 770
height 379
