### ISSUE TITLE
menus and submenus Name can not be edited

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#97]
I tried to edit some menus and sub menus name but they do not reflect on the page ,I have change the Naat videos among others but they do not reflect ,please fix this soon

**Comment by serviceproviderpk** [comment]
sub menu are not editable this hard to change them from menu.

Let me know which menu you want to rename, i will rename them.

Thanks

**Comment by regularshare** [comment]
please change the Naats Videos under the Video menu to Naija Music Videos

**Comment by NasirNiazkiyani** [comment]
ok.

**Comment by NasirNiazkiyani** [comment]
fixed...

**Comment by regularshare** [comment]
what is fixed ? where is it fixed ?  Check it well , it not yet fix

**Comment by serviceproviderpk** [comment]
let me know what you want to change more please
