### ISSUE TITLE
Replace the Wallpaper Categories

### ISSUE THREAD

**Issue by regularshare** [serviceproviderpk/RegularShare#99]
![wallpaper categories](https://cloud.githubusercontent.com/assets/19783574/17470987/a1051c92-5d38-11e6-9160-0a34bf5566ee.PNG)

From the Wallpaper Categories above ,Kindly Replace the Wallpaper Categories with more Headlines News as shown in the second picture below
![more headlines](https://cloud.githubusercontent.com/assets/19783574/17471002/bb365482-5d38-11e6-88fd-9d6aa0c99735.PNG)

Kindly make it possible for us to be able to upload embeded videos

**Comment by serviceproviderpk** [comment]
we can do it, but it will be not good we are focusing only news every where on the web site.....
